/**
 * Clears prior capture output before a run.
 *
 * screenshots/ accumulated a folder per rig per session — matrix, tooltips,
 * motion, spot, modal, before/after — plus a JSON per integrity run, and
 * nobody was pruning it. It is now purely disposable: everything in here can
 * be regenerated by re-running a script.
 *
 * Nothing of record lives here any more. The integrity ledger and the review
 * verdicts moved to records/ precisely because clearing this folder once took
 * them with it.
 */
import { readdirSync, rmSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";

const ROOT = "screenshots";

function main() {
  if (!existsSync(ROOT)) {
    mkdirSync(ROOT, { recursive: true });
    console.log("screenshots/ created (was absent)");
    return;
  }
  let dirs = 0;
  let files = 0;
  for (const entry of readdirSync(ROOT, { withFileTypes: true })) {
    const full = path.join(ROOT, entry.name);
    rmSync(full, { recursive: true, force: true });
    if (entry.isDirectory()) dirs++;
    else files++;
  }
  console.log(`cleared screenshots/: ${dirs} folder(s), ${files} file(s)`);
}

main();
